site_name: E3SM-Project

nav:
  - 'E3SM Docs': 'https://e3sm-project.github.io/E3SM'
  - 'Running E3SM': 'guide.md'

repo_name: E3SM-Project/E3SM-Project.github.io
repo_url: https://github.com/E3SM-Project/E3SM-Project.github.io

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tooltips

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - admonition
  - pymdownx.details
  - attr_list

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - redirects:
      redirect_maps:
        'e3sm.md': 'https://e3sm-project.github.io/E3SM'
